version: "3"

services:
  sveltekit:
    build:
      context: .
      dockerfile: dockerfiles/sveltekit/dev/Dockerfile
    entrypoint: ["npm", "run", "dev"]
    environment:
      - environment=cypress
      - defaultMapId=OcZm1UN6gxuUiFWTgoyp
      - fbApiKey="AIzaSyDTQTwe21wwYm2TsMBwH8m1lSHWMEK4KmQ"
      - fbAuthDomain="expwis.firebaseapp.com"
      - fbProjectId="expwis"
      - fbStorageBucket="expwis.appspot.com"
      - fbMessagingSenderId="950890412912"
      - fbAppI="1:950890412912:web:a248488bf4e6eb2bc3adb5"
      - fbMeasurementId="G-8ZT9LCY8BY"
    ports:
      - 3000:3000
      - 3001:3001
      - 9222:9222
      - 9229:9229
      - 24678:24678
      - 9005:9005
    networks:
      - internal_network

  firebase:
    build:
      context: .
      dockerfile: dockerfiles/sveltekit/dev/Dockerfile
    entrypoint: ["npm", "run", "emulate"]
    ports:
      - 5001:5001
      - 5010:5010
      - 5012:5012
      - 5014:5014
      - 4500:4500
      - 4400:4400
    networks:
      - internal_network

  cypress:
    build:
      context: .
      dockerfile: dockerfiles/cypress/Dockerfile
    env_file:
      - functional-tests/.env
    networks:
      - internal_network
  
networks:
  internal_network:
