version: "3"

services:
  sveltekit:
    build:
      context: .
      dockerfile: dockerfiles/sveltekit/dev/Dockerfile
    volumes:
      - ./:/var/www/
    environment:
      - ENVIRONMENT=development
      - FIREBASE_TOKEN=1//09M3SUzOVSCzuCgYIARAAGAkSNwF-L9IrUMKtp1MY6pl0ghbm3YawXj5NKXywlV8iI8iRMhib7VST-qhVVOPQ-HqCbLltSdQzdfs
    ports:
      - 3000:3000
      - 3001:3001
      - 9222:9222
      - 9229:9229
      - 24678:24678
      - 9005:9005
      - 5000-5030:5000-5030
      - 4500:4500
    networks:
      - internal_network

  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    volumes:
      - ./:/var/www/
    ports:
      - 8004:80
    networks:
      - internal_network
  
networks:
  internal_network:
