version: "3.9"

services:
  sveltekit:
    build:
      context: .
      dockerfile: dockerfiles/sveltekit/dev/Dockerfile
    volumes:
      - ./:/var/www/
    environment:
      - environment=cypress
      - algoliaApp=6868GHOPYM
    secrets:
      - algolia-private-api-key
    ports:
      - 3000:3000
      - 3001:3001
      - 9222:9222
      - 9229:9229
      - 24678:24678
      - 9005:9005
      - 5000-5030:5000-5030
      - 4500:4500
    networks:
      - internal_network
secrets:
  algolia-private-api-key:
    file: ./config/secret-algolia-key.txt
networks:
  internal_network:
