version: "3"

services:
  sveltekit-test:
    build:
      context: .
      dockerfile: dockerfiles/sveltekit/dev/Dockerfile
    entrypoint: ["npm", "run", "dev"]
    environment:
      - environment=test
      - algoliaApp=6868GHOPYM
    # ports:
    #   - 3000:3000
    #   - 3001:3001
    #   - 9222:9222
    #   - 9229:9229
    #   - 24678:24678
    #   - 9005:9005
    networks:
      - internal_network

  firebase:
    build:
      context: .
      dockerfile: dockerfiles/sveltekit/dev/Dockerfile
    environment:
      - algoliaApp=6868GHOPYM
      - environment=test
    entrypoint: ["npm", "run", "emulateCypress"]
    # ports:
    #   - 5001:5001
    #   - 5010:5010
    #   - 5012:5012
    #   - 5014:5014
    #   - 4500:4500
    #   - 4400:4400
    secrets:
      - algolia-private-api-key
    networks:
      - internal_network

  playwright:
    build:
      context: .
      dockerfile: dockerfiles/sveltekit/dev/Dockerfile
    volumes:
      - ./test-results/:/var/www/svelte/test-results
    environment:
      - CI=true
    networks:
      - internal_network

secrets:
  algolia-private-api-key:
    file: ./config/secret-algolia-key.txt  
networks:
  internal_network:
